language: java

jdk:
  - oraclejdk11

addons:
  postgresql: "12"

sudo: required
dist: trusty

before_script:
  - psql -c "CREATE USER planqk WITH CREATEDB CREATEUSER PASSWORD 'planqk';" -U postgres
  - psql -c 'CREATE DATABASE planqk;' -U postgres
script:
  - mvn package --fail-at-end
after_success:
  - bash <(curl -s https://codecov.io/bash)
