dist: bionic
sudo: required
language: java
jdk:
    - openjdk11
services:
    - docker

before_script:
    - docker pull postgres:12
    # TODO Consider replacing with planqk/initialized-db:latest once that image becomes mandatory
    - docker run --rm -d -p 5432:5432 -e POSTGRES_DB=planqk_test -e POSTGRES_PASSWORD=planqk -e POSTGRES_USER=planqk -d postgres
script:
    - mvn package --fail-at-end
after_success:
    - bash <(curl -s https://codecov.io/bash)
