dist: bionic
sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker

script:
  - mvn package --fail-at-end | grep -v 'at org'
after_success:
  - bash <(curl -s https://codecov.io/bash)
