dist: bionic
sudo: required
language: java
jdk:
    - openjdk11
services:
    - docker

script:
    # Filter Stacktraces to reduce log length significantly
    # Log messages and exceptions are still shown, but without
    # the attached Stacktrace
    - mvn package --fail-at-end | grep -v -E 'at .*\((.*\.java:[0-9]*|Native Method)\)|o\.h\.e\.jdbc\.spi\.SqlExceptionHelper'
after_success:
    - bash <(curl -s https://codecov.io/bash)
