version: '3.6'
services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: planqk
            POSTGRES_PASSWORD: planqk
            POSTGRES_DB: planqk
        ports:
            - "5432:5432"
