name: SwaggerUI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Fetch Data
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn package -DskipTests
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 12
        postgresql db: planqk
        postgresql user: planqk
        postgresql password: planqk
    - name: Load openapi.json
      run: |
        java -jar org.planqk.atlas.web/target/org.planqk.atlas.web.war &
        # Wait for atlas to start
        sleep 30
        curl http://localhost:8080/atlas/v3/api-docs > openapi.json
    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: swagger-ui
        spec-file: openapi.json
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: swagger-ui
